name: Update WakaTime Stats

on:
  schedule:
    - cron: '*/10 * * * *'  # This runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update WakaTime stats in README
        uses: anmol098/waka-readme-stats@v2
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

