name: Update WakaTime Stats

on:
  schedule:
    - cron: '*/10 * * * *'  # This runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update WakaTime stats in README
        uses: athul/waka-readme@master 
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: 'all_time'  # Tiempo total desde el inicio
          SHOW_TOTAL: 'true'  # Show the total time


